_wandb:
    value:
        cli_version: 0.21.1
        e:
            b6kkiso9gdngscgb9j262b7dibled4pi:
                args:
                    - --model_name
                    - black-forest-labs/FLUX.1-dev
                    - --prompts_csv
                    - /home/mtoker/git/simple_skips/sample_prompts_analysis_top10.csv
                    - --seeds
                    - 42,52,62
                    - --do_indirect_effect
                    - --do_direct_effect_removing_partial
                    - --do_direct_effect_using_only_partial
                    - --start_idx
                    - "2"
                    - --end_idx
                    - "4"
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "6746538991616"
                        used: "87662854144"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/diffusion_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-1773b000-aad5-4e3d-1f76-e63fbd4abf5b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-0dba970c-2e11-fbc8-1ff9-34704a401e98
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-8cb71957-af1e-a652-13dc-a61e9441c3c8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-def75523-0cc9-a50f-1c27-553e2273ce40
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-1d58409a-cc71-21c2-6235-1e3e7445480b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-f8d130d6-edbe-036d-67cf-6593f88dcfe5
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-d9d78735-d84a-f66c-8328-182e9f577ce2
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-9b5ca2f8-b7a5-2ee5-0086-32d2572ae2a4
                host: batch-block1-0009
                memory:
                    total: "2164258553856"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.31
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/analysis.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    cluster_name: cs-oci-ord
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus_on_node: "8"
                    gtids: "0"
                    job_account: nvr_israel_persdiff
                    job_cpus_per_node: "32"
                    job_end_time: "1762450992"
                    job_gid: "30"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_name: flux_analysis_top10_interactive
                    job_nodelist: batch-block1-0009
                    job_num_nodes: "1"
                    job_partition: interactive
                    job_qos: normal
                    job_start_time: "1762436592"
                    job_uid: "149570"
                    job_user: mtoker
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: batch-block1-0009
                    nprocs: "1"
                    prio_process: "0"
                    submit_dir: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                    submit_host: batch-block1-2006
                    task_pid: "2558977"
                    tasks_per_node: "1"
                    topology_addr: top.nw_00b0043b83efa33ec5eb7ee4e638070a0ef222ed72a8eab9127a0de4eaca6360.rk_97c6bac58e7f0c9fe454bb596db12163e4b32e914b8c702e53a0625a1d250c63.batch-block1-0009
                    topology_addr_pattern: switch.switch.switch.node
                    working_cluster: cs-oci-ord:cs-oci-ord-a:6817:9984:109
                startedAt: "2025-11-06T13:44:27.224562Z"
                writerId: b6kkiso9gdngscgb9j262b7dibled4pi
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "3":
                - 16
                - 24
            "4": 3.12.11
            "5": 0.21.1
            "6": 4.55.0
            "12": 0.21.1
            "13": linux-x86_64
device:
    value: cuda
height:
    value: 1024
model:
    value: black-forest-labs/FLUX.1-dev
negative_prompt:
    value: ""
num_inference_steps:
    value: 26
prompt:
    value: a cow looking surprised
seed:
    value: 42
subset:
    value: animals
variant:
    value: specific
width:
    value: 1024
