_wandb:
    value:
        cli_version: 0.22.2
        e:
            as8jstik3agjverskpsouyr3zseqk79s:
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "6746538991616"
                        used: "44402208768"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/grad_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-d34ecdce-2a61-4c29-de7a-80edf6b560ee
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-8c758454-fbe6-594e-8dca-8dc0fddb9699
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-30795720-4745-5d8a-74cd-bb3e9492914a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-56229a4d-ec6b-a7c6-8c95-ca04e9858490
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-0f70dbc4-f530-e0f6-f81a-7809ba7337a7
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-1473814f-9b15-4cf7-bc99-eaa023c52b91
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-bbe05a70-1be5-80f2-68c6-814b4f0585ff
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-4425c614-3d8d-c02b-35be-8ea6232b11cf
                host: batch-block5-00384
                memory:
                    total: "2164258557952"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.31
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/analysis.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                startedAt: "2025-11-11T12:33:00.744861Z"
                writerId: as8jstik3agjverskpsouyr3zseqk79s
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "3":
                - 2
                - 16
                - 24
            "4": 3.12.11
            "5": 0.22.2
            "6": 4.56.0
            "12": 0.22.2
            "13": linux-x86_64
device:
    value: cuda
height:
    value: 1024
model:
    value: black-forest-labs/FLUX.1-dev
negative_prompt:
    value: ""
num_inference_steps:
    value: 26
prompt:
    value: the white house of washington dc at dawn
seed:
    value: 42
subset:
    value: places
variant:
    value: specific
width:
    value: 1024
