_wandb:
    value:
        cli_version: 0.22.2
        e:
            lm4dtnnsfsl80kzk3k0ogbq026217a73:
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "6746538991616"
                        used: "32330678272"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/grad_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-1bf1d0b0-27c5-2b43-a040-e2da3c49dda1
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-704d681f-72ee-508c-6308-269b6b5a4ccf
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-2a5bc42e-3a63-9451-1a08-04b7b7a41fe6
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-82cc844f-f42e-2f4d-7016-5dcbeeea6254
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-bf1ce063-7ade-aaf9-df8d-c032bbf23f7c
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-b592f6c8-c352-4bb9-0c14-b1a51b1025c3
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-331743a9-9522-bd99-ca77-dea2eb540b18
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-229e6dd4-2877-2c88-e925-58adeb9d3681
                host: batch-block5-00387
                memory:
                    total: "2164258557952"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.31
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/analysis.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                startedAt: "2025-11-12T13:16:40.165315Z"
                writerId: lm4dtnnsfsl80kzk3k0ogbq026217a73
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "3":
                - 2
                - 16
            "4": 3.12.11
            "5": 0.22.2
            "6": 4.56.0
            "12": 0.22.2
            "13": linux-x86_64
device:
    value: cuda:4
height:
    value: 1024
model:
    value: black-forest-labs/FLUX.1-schnell
negative_prompt:
    value: ""
num_inference_steps:
    value: 1
prompt:
    value: the venom as a charcoal drawing
seed:
    value: 62
subset:
    value: copyrights
variant:
    value: specific
width:
    value: 1024
