_wandb:
    value:
        cli_version: 0.21.1
        e:
            iuluxt0dsb3w4gg2oznpo20qa89ybxk0:
                args:
                    - --model_name
                    - black-forest-labs/FLUX.1-dev
                    - --prompts_csv
                    - /home/mtoker/git/simple_skips/sample_prompts_with_placeholders_20_3_42.csv
                    - --generate_variants
                    - specific
                    - --start_idx
                    - "30"
                    - --end_idx
                    - "60"
                    - --num_inference_steps
                    - "26"
                    - --seeds
                    - 40,41,42,43,44,45,46,47,48,49
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "6746538991616"
                        used: "65340764160"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/diffusion_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-e75444ba-7e1d-7b28-ff83-ada391d949d0
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-43938d76-8f4c-dac2-6188-4cdbc3ea90fc
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-0383940f-11f4-c327-e6d6-64812deea971
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-241d78b9-72b4-289c-3542-51a1ad73f7a4
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-18728b60-eb50-55be-b90e-46cc49b0a5e6
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-9e223fce-bf9b-a57d-a793-9f1029dadf2b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-148b80a7-65a9-18a0-060a-328b91c82aa0
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-5a2de2a7-e580-9e8d-2f60-d429f328824a
                host: batch-block1-0047
                memory:
                    total: "2164258562048"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.31
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/main.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                startedAt: "2025-11-04T20:59:34.059456Z"
                writerId: iuluxt0dsb3w4gg2oznpo20qa89ybxk0
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "3":
                - 2
                - 16
                - 24
            "4": 3.12.11
            "5": 0.21.1
            "6": 4.55.0
            "12": 0.21.1
            "13": linux-x86_64
device:
    value: cuda
height:
    value: 1024
model:
    value: black-forest-labs/FLUX.1-dev
negative_prompt:
    value: ""
num_inference_steps:
    value: 26
prompt:
    value: a lion in a comic book style
seed:
    value: 40
subset:
    value: animals
variant:
    value: specific
width:
    value: 1024
