_wandb:
    value:
        cli_version: 0.22.2
        e:
            v9ku7q8t7uop8xeboorlb3dctofm6ut4:
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "6746538991616"
                        used: "69045841920"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/grad_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-c2da172d-ce4d-4163-1dc4-c314a27ce03d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-c38fad4a-65fa-8e64-e20c-eaea78757701
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-d216c9f9-d6d7-617f-c563-e7ef0d41a60f
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-89e9f4ca-3d27-9e2d-937f-903c2a2a90a5
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-cdb08fa8-5d9c-8702-e639-777e499fde4b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-ca79cd9c-562a-9b06-5650-822e5753f045
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-33b83c49-13ae-2b18-49fd-238b4b3885a8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-2936875c-636d-7885-f9fe-120917c0a7a7
                host: batch-block1-0048
                memory:
                    total: "2164258562048"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.31
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/main.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                startedAt: "2025-10-30T08:56:15.581100Z"
                writerId: v9ku7q8t7uop8xeboorlb3dctofm6ut4
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "3":
                - 2
                - 16
            "4": 3.12.11
            "5": 0.22.2
            "6": 4.56.0
            "12": 0.22.2
            "13": linux-x86_64
device:
    value: cuda:2
height:
    value: 512
model:
    value: black-forest-labs/FLUX.1-dev
negative_prompt:
    value: ""
num_inference_steps:
    value: 26
prompt:
    value: A photo of Bordeaux
seed:
    value: 46
width:
    value: 512
