_wandb:
    value:
        cli_version: 0.21.1
        e:
            l6mrvreth7as73094npnx3gwuqbcm4qb:
                args:
                    - --model_name
                    - black-forest-labs/FLUX.1-dev
                    - --prompts_csv
                    - /home/mtoker/git/simple_skips/sample_prompts_with_placeholders_20_3_42.csv
                    - --generate_variants
                    - specific
                    - --start_idx
                    - "90"
                    - --end_idx
                    - "120"
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "6746538991616"
                        used: "45748436992"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/diffusion_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-0d40ac9e-6674-2375-8f69-f2565fe44588
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-ee9a1b03-2c81-adf3-be47-6055506c9068
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-b9e91051-b9cc-4565-f4e2-1317c95c0e8f
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-d5ff67d6-338c-b971-1331-39c11fcdb019
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-c5bfe07f-6ed2-dbe1-2854-6450735dc422
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-66813036-6471-15fc-2cc8-10f7575dac7d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-b21b09f2-c1ac-051b-417c-ee0c7b9882c3
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-eefbce9f-cd7e-4ced-b0e2-abfda1668cc0
                host: batch-block1-2114
                memory:
                    total: "2164258562048"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.31
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/main.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    cluster_name: cs-oci-ord
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    export_env: ALL,GEN_PROMPTS_CSV=/home/mtoker/git/simple_skips/sample_prompts_with_placeholders_20_3_42.csv
                    get_user_env: "1"
                    gpus_on_node: "8"
                    gtids: "0"
                    job_account: nvr_israel_persdiff
                    job_cpus_per_node: "32"
                    job_end_time: "1762356055"
                    job_gid: "30"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_name: flux_8gpu_interactive
                    job_nodelist: batch-block1-2114
                    job_num_nodes: "1"
                    job_partition: interactive
                    job_qos: normal
                    job_start_time: "1762341655"
                    job_uid: "149570"
                    job_user: mtoker
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: batch-block1-2114
                    nprocs: "1"
                    prio_process: "0"
                    submit_dir: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                    submit_host: batch-block4-0027
                    task_pid: "515336"
                    tasks_per_node: "1"
                    topology_addr: top.nw_a283cf568a6a27bb40a29e9e1dd3e5fb886858b044a2b4cfa3f77e17d0688250.rk_e6278a94525ea20e2e107108bcfb2ed2abb96c7688ed4775d782de637c8edb3e.batch-block1-2114
                    topology_addr_pattern: switch.switch.switch.node
                    working_cluster: cs-oci-ord:cs-oci-ord-a:6817:9984:109
                startedAt: "2025-11-05T11:30:47.391511Z"
                writerId: l6mrvreth7as73094npnx3gwuqbcm4qb
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "3":
                - 2
                - 16
                - 24
            "4": 3.12.11
            "5": 0.21.1
            "6": 4.55.0
            "12": 0.21.1
            "13": linux-x86_64
device:
    value: cuda
height:
    value: 1024
model:
    value: black-forest-labs/FLUX.1-dev
negative_prompt:
    value: ""
num_inference_steps:
    value: 26
prompt:
    value: beyonce walking down a narrow alley
seed:
    value: 42
subset:
    value: celebrities
variant:
    value: specific
width:
    value: 1024
