_wandb:
    value:
        cli_version: 0.21.1
        e:
            6nsl5s8fyylp4hc1fjylqttimm3dz3qp:
                args:
                    - --start_idx
                    - "3"
                    - --end_idx
                    - "6"
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "20321311363072"
                        used: "4195566518272"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/diffusion_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-27f60f46-a27b-d3c5-8873-384b4f480bcb
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-40a2e2e2-ee10-7d1c-7480-f951ccd7c7dc
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-c47225c0-1f1c-a458-0147-6b587ac47617
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-8ec39704-d027-a634-8d2b-529d620a3923
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-7e497a00-08ac-835d-7208-2e3c8750fb66
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-756ddb08-445e-1df6-d997-4b23120c0a2a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-68a0b951-3e92-6f42-0579-0c454c3b4045
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-777f23d2-c5d0-63a2-ee17-cc602c4bdbfc
                host: batch-block1-10019
                memory:
                    total: "2164258553856"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.35
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/analysis.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    cluster_name: cs-oci-ord
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    cpu_bind_list: 0x00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpu_freq_req: Performance
                    cpus_on_node: "248"
                    cpus_per_task: "240"
                    distribution: cyclic
                    do_autoreboot: "0"
                    gpus_on_node: "8"
                    gtids: "0"
                    job_account: nvr_israel_persdiff
                    job_cpus_per_node: "248"
                    job_end_time: "1762189905"
                    job_gid: "30"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_name: flux_analysis_20251103-051135
                    job_nodelist: batch-block1-10019
                    job_num_nodes: "1"
                    job_partition: interactive
                    job_qos: normal
                    job_start_time: "1762175505"
                    job_uid: "149570"
                    job_user: mtoker
                    launch_node_ipaddr: 10.49.162.161
                    mem_per_node: "1843200"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: batch-block1-10019
                    nprocs: "1"
                    ntasks_per_node: "1"
                    open_mode: a
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "12255"
                    prio_process: "0"
                    srun_comm_host: 10.49.162.161
                    srun_comm_port: "23187"
                    step_gpus: 0,1,2,3,4,5,6,7
                    step_id: "0"
                    step_launcher_port: "23187"
                    step_nodelist: batch-block1-10019
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                    submit_host: batch-block1-10013
                    task_pid: "772552"
                    tasks_per_node: "1"
                    topology_addr: top.nw_a283cf568a6a27bb40a29e9e1dd3e5fb886858b044a2b4cfa3f77e17d0688250.rk_efacc78394cb7b7083d641eac2b02c31be2a38e111b25ff754a9a5dfaa1517e3.batch-block1-10019
                    topology_addr_pattern: switch.switch.switch.node
                    umask: "0022"
                    working_cluster: cs-oci-ord:cs-oci-ord-a:6817:9984:109
                startedAt: "2025-11-03T13:13:47.830913Z"
                writerId: 6nsl5s8fyylp4hc1fjylqttimm3dz3qp
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "3":
                - 2
                - 16
            "4": 3.12.11
            "5": 0.21.1
            "6": 4.55.0
            "12": 0.21.1
            "13": linux-x86_64
device:
    value: cuda
height:
    value: 1024
model:
    value: black-forest-labs/FLUX.1-dev
negative_prompt:
    value: ""
num_inference_steps:
    value: 26
prompt:
    value: a camel walking along a riverbank
seed:
    value: 87
subset:
    value: animals
variant:
    value: specific
width:
    value: 1024
