_wandb:
    value:
        cli_version: 0.21.1
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "3":
                - 16
            "4": 3.12.11
            "5": 0.21.1
            "6": 4.55.0
            "12": 0.21.1
            "13": linux-x86_64
device:
    value: cuda
height:
    value: 1024
model:
    value: black-forest-labs/FLUX.1-schnell
negative_prompt:
    value: ""
num_inference_steps:
    value: 1
prompt:
    value: a cow as a charcoal drawing
seed:
    value: 42
subset:
    value: animals
variant:
    value: specific
width:
    value: 1024
