_wandb:
    value:
        cli_version: 0.21.1
        e:
            hxxb1coo70caxeor3d4r4zcsj5fqg8u2:
                args:
                    - --start_idx
                    - "150"
                    - --end_idx
                    - "180"
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "6746538991616"
                        used: "47946432512"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/diffusion_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-1f924430-5414-64ef-dee2-890e936dbb5d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-3dcf8652-17df-732c-8997-5a1ac33c6f22
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-a190bd0e-8c50-6f7d-c9ae-b86a03f2e59f
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-89135c66-e427-ebad-f63c-27f0e71b054f
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-19b17ff2-671d-0f3b-00e4-7425b76b30cc
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-f877e6eb-385d-2df7-c9f5-f2d53a7d8639
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-44098f18-5fa7-bc5e-5003-5755024fbbaa
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-104ac420-eaef-c442-4645-bb0dc1947e3f
                host: batch-block1-0082
                memory:
                    total: "2164258557952"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.31
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/main.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                startedAt: "2025-11-04T12:24:33.441200Z"
                writerId: hxxb1coo70caxeor3d4r4zcsj5fqg8u2
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "3":
                - 2
                - 16
                - 24
            "4": 3.12.11
            "5": 0.21.1
            "6": 4.55.0
            "12": 0.21.1
            "13": linux-x86_64
device:
    value: cuda
height:
    value: 1024
model:
    value: black-forest-labs/FLUX.1-dev
negative_prompt:
    value: ""
num_inference_steps:
    value: 26
prompt:
    value: a character as a hologram
seed:
    value: 42
subset:
    value: copyrights
variant:
    value: placeholder
width:
    value: 1024
