_wandb:
    value:
        cli_version: 0.21.1
        e:
            dnu3pov2w39mbgzjnd6dqxy5rbvp7yem:
                args:
                    - --model_name
                    - black-forest-labs/FLUX.1-dev
                    - --prompts_csv
                    - /home/mtoker/git/simple_skips/sample_prompts_with_placeholders_20_3_42.csv
                    - --generate_variants
                    - specific
                    - --seeds
                    - 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
                    - --start_idx
                    - "120"
                    - --end_idx
                    - "160"
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "6746538991616"
                        used: "53734752256"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/diffusion_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-ac8756c3-1291-4040-ebfd-4f0c6a6a1e1c
                host: batch-block4-1017
                memory:
                    total: "2164258557952"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.31
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/main.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    cluster_name: cs-oci-ord
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: nvr_israel_persdiff
                    job_cpus_per_node: "8"
                    job_end_time: "1762432404"
                    job_gid: "30"
                    job_gpus: "0"
                    job_name: fluxdev_polar_main_3_120_160
                    job_nodelist: batch-block4-1017
                    job_num_nodes: "1"
                    job_partition: polar
                    job_qos: normal
                    job_start_time: "1762418004"
                    job_uid: "149570"
                    job_user: mtoker
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: batch-block4-1017
                    prio_process: "0"
                    submit_dir: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                    submit_host: batch-block1-2004
                    task_pid: "154248"
                    tasks_per_node: "1"
                    topology_addr: top.nw_8919f0d7ebfb26b1bfed3efe66ed8dbf6127d6c4f76cfd02e8ae08e550b51672.rk_4cf8fae6df9402f123c5fe6d0c34d4576feecf62653bca185f7cbbd3b81bb02b.batch-block4-1017
                    topology_addr_pattern: switch.switch.switch.node
                    working_cluster: cs-oci-ord:cs-oci-ord-a:6817:9984:109
                startedAt: "2025-11-06T11:49:53.169325Z"
                writerId: dnu3pov2w39mbgzjnd6dqxy5rbvp7yem
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "3":
                - 2
                - 16
                - 24
            "4": 3.12.11
            "5": 0.21.1
            "6": 4.55.0
            "12": 0.21.1
            "13": linux-x86_64
device:
    value: cuda
height:
    value: 1024
model:
    value: black-forest-labs/FLUX.1-dev
negative_prompt:
    value: ""
num_inference_steps:
    value: 26
prompt:
    value: mike wazowski on a hot summer day
seed:
    value: 0
subset:
    value: copyrights
variant:
    value: specific
width:
    value: 1024
