_wandb:
    value:
        cli_version: 0.22.2
        e:
            j84puhdu6h23banl7ho34gvuclibmv6b:
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "6746538991616"
                        used: "84109492224"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/grad_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-a574d69c-ed84-98ee-8367-6e4c86a8da27
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-08cdf592-b242-3cd1-d2e4-a5452bf6b9fe
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-e3f71729-e372-1c4b-f23f-dca7069d8005
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-f17712d1-9bb1-a597-511b-fb253f20e16d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-db02503a-48a6-1e97-7eec-dd4cea0e9f4a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-61a68201-5f16-6257-5b3f-2eea6d1cdb52
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-8e978682-d456-0f2f-15f6-3c5275adc4f4
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-451f36dd-e68c-699e-a8f3-5af75368399e
                host: batch-block1-0023
                memory:
                    total: "2164258557952"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.31
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/main.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                startedAt: "2025-10-26T10:17:21.471374Z"
                writerId: j84puhdu6h23banl7ho34gvuclibmv6b
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "3":
                - 2
                - 16
            "4": 3.12.11
            "5": 0.22.2
            "6": 4.56.0
            "12": 0.22.2
            "13": linux-x86_64
device:
    value: cuda:1
height:
    value: 768
model:
    value: black-forest-labs/FLUX.1-schnell
num_inference_steps:
    value: 5
prompt:
    value: A photo of spongebob on a sunny beach
seed:
    value: 42
width:
    value: 768
