_wandb:
    value:
        cli_version: 0.21.1
        e:
            t7nro5zfp5purqy7bghusghbyewi2ynk:
                args:
                    - --model_name
                    - black-forest-labs/FLUX.1-dev
                    - --prompts_csv
                    - /home/mtoker/git/simple_skips/sample_prompts_analysis_top10.csv
                    - --seeds
                    - 42,52,62
                    - --do_indirect_effect
                    - --do_direct_effect_removing_partial
                    - --do_direct_effect_using_only_partial
                    - --start_idx
                    - "2"
                    - --end_idx
                    - "4"
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "6746538991616"
                        used: "84009398272"
                email: mtoker@nvidia.com
                executable: /lustre/fsw/portfolios/nvr/users/mtoker/miniconda3/envs/diffusion_env/bin/python
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-544c1426-e3fd-b0bd-f8a4-8403905a915b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-850163ac-3c75-805f-0693-aae45a6dd8e6
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-96085145-1be5-a551-e7be-5e3e1ee1d605
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-2534b7bb-ee9d-3abd-2cef-9a0caf7c3e39
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-6b243733-2107-bbbb-142c-5ca4c639323c
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-e2495f95-9955-d848-5f14-0a70783d6153
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-dcc31f17-f52b-d8fd-06bd-a42d520f51a3
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-c97119f9-a3f1-7056-972a-d6bfb3ecd1ef
                host: batch-block1-0081
                memory:
                    total: "2164258562048"
                os: Linux-5.15.0-1032-oracle-x86_64-with-glibc2.31
                program: /home/mtoker/git/simple_skips/sandbox_diffusers/analysis.py
                python: CPython 3.12.11
                root: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                slurm:
                    cluster_name: cs-oci-ord
                    conf: /cm/shared/apps/slurm/var/etc/cs-oci-ord/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus_on_node: "8"
                    gtids: "0"
                    job_account: nvr_israel_persdiff
                    job_cpus_per_node: "32"
                    job_end_time: "1762532086"
                    job_gid: "30"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_name: flux_analysis_top10_interactive
                    job_nodelist: batch-block1-0081
                    job_num_nodes: "1"
                    job_partition: interactive
                    job_qos: normal
                    job_start_time: "1762517686"
                    job_uid: "149570"
                    job_user: mtoker
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: batch-block1-0081
                    nprocs: "1"
                    prio_process: "0"
                    submit_dir: /lustre/fs12/portfolios/nvr/projects/nvr_israel_persdiff/users/mtoker/git/simple_skips
                    submit_host: batch-block7-01357
                    task_pid: "3252479"
                    tasks_per_node: "1"
                    topology_addr: top.nw_00b0043b83efa33ec5eb7ee4e638070a0ef222ed72a8eab9127a0de4eaca6360.rk_37944d6f03ffc51c03489d8e69fef2bfa2cec90074e51b2b9215580e733e32f4.batch-block1-0081
                    topology_addr_pattern: switch.switch.switch.node
                    working_cluster: cs-oci-ord:cs-oci-ord-a:6817:9984:109
                startedAt: "2025-11-07T12:15:57.905189Z"
                writerId: t7nro5zfp5purqy7bghusghbyewi2ynk
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "3":
                - 2
                - 16
                - 24
            "4": 3.12.11
            "5": 0.21.1
            "6": 4.55.0
            "12": 0.21.1
            "13": linux-x86_64
device:
    value: cuda
height:
    value: 1024
model:
    value: black-forest-labs/FLUX.1-dev
negative_prompt:
    value: ""
num_inference_steps:
    value: 26
prompt:
    value: a cow looking surprised
seed:
    value: 42
subset:
    value: animals
variant:
    value: specific
width:
    value: 1024
